---
title: "Reisepartizipation"
author: "Alexander Bauer, Maximilian Weigert"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    number_sections: yes
    code_folding: hide
  pdf_document:
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(APCtools)
library(tidyverse)
theme_set(theme_minimal())
library(mgcv)
library(pROC)

# read and prepare the data
source("../0_helpers/1_dataPrep.R")
dat_model <- read_and_prepare_data(user = "Alex", model = "participation")
```

# Model
```{r}
# pure APC model, without covariates
model <- bam(formula = y_atLeastOneUR ~ te(period, age, k = c(10, 10), bs = "ps"),
                 family = binomial(link = "logit"), data = dat_model)

# model including covariates
model_L <- bam(formula = y_atLeastOneUR ~ te(period, age, k = c(10, 10), bs = "ps") +
                   S_Geschlecht + S_Kinder_0_bis_5_binaer + S_Wohnortgroesse +
                   S_Bildung_HV + s(S_Einkommen_HH_equi, bs = "ps", k =10) +
                 S_Haushaltsgroesse,
                 family = binomial(link = "logit"), data = dat_model)

```

##### Heatmap of APC surface 

```{r}
plot_APCheatmap(dat = dat_model, model = model,   plot_CI = TRUE)
plot_APCheatmap(dat = dat_model, model = model_L, plot_CI = TRUE)
```

##### Marginal APC effects

```{r}
model_list <- list("Pure APC model"  = model,
                   "Covariate model" = model_L)
plot_jointMarginalAPCeffects(model_list, dat_model)
```


##### Partial APC plots 
```{r}
plot_partialAPCeffects(model, dat_model, variable = "age")
plot_partialAPCeffects(model, dat_model, variable = "period")
plot_partialAPCeffects(model, dat_model, variable = "cohort")
```

##### Partial APC plots (incl. covariates)
```{r}
plot_partialAPCeffects(model_L, dat_model, variable = "age")
plot_partialAPCeffects(model_L, dat_model, variable = "period")
plot_partialAPCeffects(model_L, dat_model, variable = "cohort")
```


##### Effects of further covariates 
```{r}
plot_1Dsmooth(model_L, select = 2)
plot_linearEffects(model_L)
```


##### Modellevaluation 

```{r}
set.seed(3456)
  
# Splitting the data into training and test data:
train_index <- sample(1:nrow(dat_model), 0.8 * nrow(dat_model))
dat_train <- dat_model[train_index, ]
dat_test <- dat_model[-train_index, ]

# Model estimation:
model_pure <- bam(formula = y_atLeastOneUR ~ te(period, age, k = c(10, 10), bs = "ps"),
                  family = binomial(link = "logit"), data = dat_train)
  
# Computation of AUC:
prediction <- predict(object = model_pure, newdata = dat_test)
auc <- suppressMessages(roc(dat_test$y_atLeastOneUR, prediction))
auc 
```

##### Modellevaluation (incl. Covariables)

```{r}
# Model estimation:
model_covariate <- bam(formula = y_atLeastOneUR ~ te(period, age, k = c(10, 10), bs = "ps")+
                   S_Geschlecht + S_Kinder_0_bis_5_binaer + S_Wohnortgroesse +
                   S_Bildung_HV + s(S_Einkommen_HH, bs = "ps", k =10) +
                 S_Haushaltsgroesse,
                 family = binomial(link = "logit"), data = dat_train)
  
# Computation of AUC:
prediction <- predict(object = model_covariate, newdata = dat_test)
auc <- suppressMessages(roc(dat_test$y_atLeastOneUR, prediction))
auc 
```
